id: P004257
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:05:17.812324
source_metadata:
  id: bdr:W3CN4780
  title: དཀའ་ཆེན་ངག་སྒྲོས།
  author: ''
  volumes:
    3cd975c011704cfa91ca134bea679130:
      image_group_id: I3CN8691
      title: ''
      volume_number: 1
      total_pages: 250
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
